config/routes.rb
Rails.application.routes.draw do
  resources :storymaps do
    resources :stories, :except => [:update, :destory]
  end
  resources :stories, :only => [:update, :destory]

  root 'storymaps#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :storymap

  enum story_type: {backbone: 0, userstory: 1}
end

app/models/storymap.rb
class Storymap < ActiveRecord::Base
  belongs_to :user
  has_many :stories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :storymaps
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, unless: -> { request.xhr? }
  protect_from_forgery with: :null_session, if: -> { request.xhr? }

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authorize
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @storymap = Storymap.find(params[:storymap_id])
    @story = @storymap.stories.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story.storymap, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story.storymap, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :story_type, :storymap_id)
    end
end

app/controllers/storymaps_controller.rb
class StorymapsController < ApplicationController
  before_filter :authorize
  before_action :set_storymap, only: [:show, :edit, :update, :destroy]

  # GET /storymaps
  # GET /storymaps.json
  def index
    @storymaps = Storymap.all
  end

  # GET /storymaps/1
  # GET /storymaps/1.json
  def show
  end

  # GET /storymaps/new
  def new
    @storymap = Storymap.new
  end

  # GET /storymaps/1/edit
  def edit
  end

  # POST /storymaps
  # POST /storymaps.json
  def create
    @storymap = @current_user.storymaps.new(storymap_params)

    respond_to do |format|
      if @storymap.save
        format.html { redirect_to storymaps_url, notice: 'Storymap was successfully created.' }
        format.json { render :show, status: :created, location: @storymap }
      else
        format.html { render :new }
        format.json { render json: @storymap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storymaps/1
  # PATCH/PUT /storymaps/1.json
  def update
    respond_to do |format|
      if @storymap.update(storymap_params)
        format.html { redirect_to storymaps_url, notice: 'Storymap was successfully updated.' }
        format.json { render :show, status: :ok, location: @storymap }
      else
        format.html { render :edit }
        format.json { render json: @storymap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storymaps/1
  # DELETE /storymaps/1.json
  def destroy
    @storymap.destroy
    respond_to do |format|
      format.html { redirect_to storymaps_url, notice: 'Storymap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storymap
      @storymap = Storymap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storymap_params
      params.require(:storymap).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/storymaps_helper.rb
module StorymapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storymapper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :story_type %><br>
    <%= f.select :story_type, Story.story_types.keys %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', storymap_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Story type</th>
      <th>Storymap</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.story_type %></td>
        <td><%= story.storymap %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Story type:</strong>
  <%= @story.story_type %>
</p>

<p>
  <strong>Storymap:</strong>
  <%= @story.storymap %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/storymaps/_form.html.erb
<%= form_for(@storymap) do |f| %>
  <% if @storymap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storymap.errors.count, "error") %> prohibited this storymap from being saved:</h2>

      <ul>
      <% @storymap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/storymaps/edit.html.erb
<h1>Editing Storymap</h1>

<%= render 'form' %>

<%= link_to 'Show', @storymap %> |
<%= link_to 'Back', storymaps_path %>

app/views/storymaps/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @current_user.name %>'s Storymaps</h1>

<%= link_to 'New Storymap', new_storymap_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @storymaps.each do |storymap| %>
      <tr>
        <td><%= storymap.name %></td>
        <td><%= storymap.description %></td>
        <td><%= storymap.updated_at %></td>
        <td><%= link_to 'Show', storymap %></td>
        <td><%= link_to 'Edit', edit_storymap_path(storymap) %></td>
        <td><%= link_to 'Destroy', storymap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/storymaps/new.html.erb
<h1>New Storymap</h1>

<%= render 'form' %>

<%= link_to 'Back', storymaps_path %>

app/views/storymaps/show.html.erb
<p id="notice"><%= notice %></p>


<h2><%= @storymap.name %> Storymap</h2>
<p>
  <%= @storymap.description %>
</p>

<h2>Stories</h2>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @storymap.stories.each do |story| %>
    <tr>
      <td><%= story.title %></td>
      <td><%= story.story_type %></td>
      <td><%= story.created_at %></td>
      <td><%= link_to 'Edit', edit_storymap_story_path(@storymap, id: story.id) %> | <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<h2>Add a story:</h2>
<%= form_for ([@storymap,@storymap.stories.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :story_type %><br>
    <%= f.select :story_type, Story.story_types.keys %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_storymap_path(@storymap) %> |
<%= link_to 'Back', storymaps_path %>

app/views/users/new.html.erb
<h1>Register for StoryMapper</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>